name: tac
description: An advanced command-line calculator.
version: 0.1.0
publish_to: "none"
repository: https://github.com/joranmulderij/tac
environment:
  sdk: ^3.5.0

dependency_overrides:
  win32: ^5.5.4

dependencies:
  ansicolor: ^2.0.1
  args: ^2.4.2
  collection: ^1.18.0
  console: ^4.1.0
  dart_console: ^4.1.0
  equatable: ^2.0.5
  hotreloader: ^4.1.0
  http: ^1.2.1
  meta: ^1.11.0
  petitparser:
    git:
      url: https://github.com/joranmulderij/dart-petitparser
  rational: ^2.2.2
  termlib: ^0.4.0
  termparser: ^0.3.0
  termunicode: ^0.1.0
  win32: ^5.5.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
