remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: TAC Advanced Calculator
description: An advanced math- and engineering-oriented command-line calculator
